# Generated by Django 4.1.6 on 2023-08-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuserscore',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
