# Generated by Django 4.1.6 on 2023-09-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quizuserscore_is_attempted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
